name: p4ls

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: cargo publish --token "$CRATES_IO_TOKEN"
